flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: false
    old-locale: false
    network-uri: true
packages:
- '.'
extra-deps:
- 'cmark-0.5.0'
- 'pandoc-citeproc-0.9'
- 'pandoc-types-1.16.0.1'
# Use older aeson to avoid excessive memory use in compilation:
- 'aeson-0.8.0.2'
resolver: lts-4.0
